import { z } from "zod"

/**
 * Vocabulary shared by every engine entity. Nothing here knows what a vertical is.
 */

/** Every row gets one. Generated by the database, not by application code. */
export const id = z.uuid()
export type Id = z.infer<typeof id>

/**
 * Which vertical a row belongs to. Stamped on every Mention, Evidence, HarvestRun
 * and Session so a single database can carry more than one pack's work without the
 * engine learning what any of them mean.
 */
export const domainId = z.string().min(1)
export type DomainId = z.infer<typeof domainId>

/**
 * Which adapter produced a row. Adapters are per-source, not per-domain: one
 * adapter serves every pack that names it.
 */
export const sourceId = z.string().min(1)
export type SourceId = z.infer<typeof sourceId>

/** ISO 3166-1 alpha-2, lowercased — the form the proxy layer takes. */
export const countryCode = z
  .string()
  .length(2)
  .regex(/^[a-z]{2}$/, "country must be lowercase ISO 3166-1 alpha-2")
export type CountryCode = z.infer<typeof countryCode>

/** BCP 47, loosely. We store what the source reported rather than normalising it away. */
export const locale = z.string().min(2)
export type Locale = z.infer<typeof locale>

/** A key in object storage. The engine never dereferences one; it hands it to the caller. */
export const storageRef = z.string().min(1)
export type StorageRef = z.infer<typeof storageRef>

/**
 * The opaque pointer from an engine row to a vertical's entity. Deliberately not a
 * foreign key: the engine must not import a pack's tables, and a pack must be
 * droppable without a migration against engine tables. The pack's `EntityRepo`
 * resolves the pair.
 */
export const entityRef = z.object({
  domainId,
  entityId: id,
})
export type EntityRef = z.infer<typeof entityRef>

/**
 * One reason a score came out the way it did. Product principle 3 — show the
 * algorithm — is satisfied by these, so every scoring factor must produce one.
 */
export const explanation = z.object({
  factor: z.string().min(1),
  contribution: z.number(),
  evidenceIds: z.array(id),
})
export type Explanation = z.infer<typeof explanation>

/**
 * A pack's scores, as stored. The engine knows the shape and nothing about the
 * meaning: which scores exist, and what each one is called, is the pack's business.
 */
export const score = z.object({
  value: z.number(),
  because: z.array(explanation),
})
export type Score = z.infer<typeof score>

export const scoreSet = z.record(z.string(), score)
export type ScoreSet = z.infer<typeof scoreSet>

/** Added to every entity. Executors do not repeat these per schema. */
export const timestamps = z.object({
  createdAt: z.date(),
  updatedAt: z.date(),
})
